id: hl7.fhir.fi.smart
canonical: https://hl7.fi/fhir/finnish-smart
name: FinnishSmart
title: Finnish Implementation Guide for SMART App Launch 
description: Guidelines for using the SMART App Launch mechanism in Finland.
status: draft # draft | active | retired | unknown
version: 0.3.0
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2022+
releaseLabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
jurisdiction: urn:iso:std:iso:3166#FI "Finland" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: HL7 Finland
  url: https://www.hl7.fi/
  # email: mikael@sensotrend.com

dependencies:
  hl7.fhir.uv.ipa: 0.1.0
  hl7.fhir.uv.smart-app-launch: 2.0.0

pages:
  index.md:
    title: Home
  examples.md:
    title: Examples
  downloads.md:
    title: Downloads
  history.md:
    title: Version History

menu:
  Home: index.html
  Examples: examples.html
  Downloads: downloads.html
