# This workflow sets up the IG publisher in a Docker container, runs sushi conversions, and
# publishes the results with GitHub Pages.

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update the image to the latest publisher
      uses: docker://hl7fhir/ig-publisher-base:latest
      with:
        # Get the latest publisher - don't run the batch script but run the line directly
        args: curl -L https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar -o ./input-cache/publisher.jar --create-dirs
    - name: Run the IG publisher
      uses: docker://hl7fhir/ig-publisher-base:latest
      with:
        # Run the publisher - don't run the batch script but run the line directly
        args: java -jar ./input-cache/publisher.jar publisher -ig .
    - name: Setup Pages
      uses: actions/configure-pages@v2
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: './output'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
